
server:
 port: 5454
 servlet:
  context-path: /restkafka
app:
 topic:
  name: test-topic
spring:
 kafka:
  producer:
   bootstrap-servers: 'localhost:9092'
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.apache.kafka.common.serialization.StringSerializer

   
  consumer:
   bootstrap-servers: 'localhost:9092'
   key-serializer: org.apache.kafka.common.serialization.StringDeserializer
   value-serializer: org.apache.kafka.common.serialization.StringDeserializer
  