server:
 port: 9793
spring:
 application:
  name: zull-server
eureka:
 client:
  service-url:
   default-zone: http://localhost:8761/eureka
zuul:
 routes:
  fpkt:
   path: /shopping-controller/select-prod
   service-id: FLIP-KART-SHOPPING
  bill:
   path: /billing-controller/calc-bill
   service-id: BILLING-SERVICE
