server:
 port: 5050
spring:
 application:
  name: resillience4j

resilience4j.circuitbreaker:
  instances:
    myCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      eventConsumerBufferSize: 10
resilience4j.retry:
 instances:
   myRetry:
     maxAttempts: 5
     waitDuration: 2000