server:
 port: 9797
spring:
 application:
   name: api-gateway
 cloud: 
  gateway:
   discovery.locator:
    enabled: true
    lowerCaseServiceId: true
    routes:
    - id: filp-kart-shopping
      uri: lb://filp-kart-shopping
      predicates:
        - Path= /shopping-controller/**
    - id: billing-service
      uri: lb://billing-service
      predicates: 
        - Path= /billing-controller/**
eureka:
 client:
  service-url:
   default-zone: http://localhost:8761/eureka