
server:
 port: 8888
spring:
 profiles:
  active: native
 cloud:
  config:
   server:
    native:
     search-locations: classpath:/config # application.yml file of config server proj is override the external files
    git:
     uri: https://github.com/ashokitschool/configuration_properties
     clone-on-start: true
#     uri: https://gitlab.com/sivakrishna4/mini_cricket_proj01.git
#     clone-on-start: true
#     username: sivakrishnavelpula
#     password: velpulasi1@2